{"status": "resolved", "priority": "feature", "title": "Test for Bugzilla importer error catcher", "milestone": "", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "", "waitingon": "", "keywords": [], "id": "108", "files": [{"url": "http://openhatch.org/bugs/file44/simplified_bugzilla_test_fails.patch", "author": "pythonian4000"}, {"url": "http://openhatch.org/bugs/file43/test_for_bugzilla_error_catcher.patch", "author": "pythonian4000"}], "history": [{"message": "assertRaises takes a callable as the last parameter. Take a careful look at\norigin/master, where I've applied these changes and one extra commit.\n\nResolved, I think!\n   \n", "author": "paulproteus"}, {"message": "Here is my attempt at a rewrite. One of the tests works fine, but the other is\nweird... assertRaises doesn't seem to be working properly (or I fail at coding).\n   \n", "author": "pythonian4000"}, {"message": "Can you rewrite the second one to use self.assertRaises (as documented in the\nPython unittest module)?\n\nI like where this is going!\n   \n", "author": "paulproteus"}, {"message": "Here is the requested test for the Bugzilla tracker error catcher in the daily\nbug importer.\n   \n", "author": "pythonian4000"}]}