{"status": "resolved", "priority": "bug", "title": "SVN mission throws HTTP 500 error", "milestone": "", "superceder": "", "nosylist": ["paulproteus, pythonian4000, stump"], "assigned": "stump", "waitingon": "", "keywords": [], "id": "120", "files": [], "history": [{"message": "Hey, Jack,\n\nThis issue hit a few users on the web, too. We should have fixed it when you\nfiled it!\n\nI'm marking this as resolved now that I've deployed a fix for it.\n   \n", "author": "paulproteus"}, {"message": "This error occurs in the second part of the SVN mission. The following section\npasses:\n\n\"Index: README\n... Rest of the diff ...\n   -- Mr. Bad\n \"\n\nNotice the space at the very end. If this space is missing then a HTTP 500 is\nthrown. If there are EXTRA spaces more than just one then we get a nice mission\nerror saying that \"The patch will not apply correctly to the latest revision.\"\nThe 500 also occurs if random junk is submitted (but submitting nothing has a\nnice error).\n\nAsheesh found the following traceback which at first glance seems to cover most\n(if not all) of the problem:\n\n--------------------------------------\nTraceback (most recent call last):\n\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/core/handlers/base.py\n\", line 99, in get_response\n    response = callback(request, *callback_args, **callback_kwargs)\n\n  File\n\"/home/deploy/milestone-a.buildout/parts/production/django/contrib/auth/decorato\nrs.py\", line 78, in __call__\n    return self.view_func(request, *args, **kwargs)\n\n  File \"/home/deploy/milestone-a.buildout/mysite/missions/views.py\", line 340,\nin svn_diff_submit\n\ncontrollers.SvnDiffMission.validate_diff_and_commit_if_ok(request.user.username,\n form.cleaned_data['diff'])\n\n  File \"/home/deploy/milestone-a.buildout/mysite/missions/controllers.py\", line\n321, in validate_diff_and_commit_if_ok\n    the_patch = patch.fromstring(diff)\n\n  File \"/home/deploy/milestone-a.buildout/mysite/missions/patch.py\", line 67,\nin fromstring\n    return Patch( StringIO(s) )\n\n  File \"/home/deploy/milestone-a.buildout/mysite/missions/patch.py\", line 118,\nin __init__\n    self.parse(stream)\n\n  File \"/home/deploy/milestone-a.buildout/mysite/missions/patch.py\", line 323,\nin parse\n    warning(\"patch file incomplete - %s\" % filename)\n\nNameError: global name 'filename' is not defined\n--------------------------------------\n   \n", "author": "pythonian4000"}]}