{"status": "resolved", "priority": "bug", "title": "Bug importer breaks when a previously-present Trac bug has been deleted", "milestone": "", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "", "waitingon": "", "keywords": [], "id": "122", "files": [{"url": "http://openhatch.org/bugs/file62/delete_Trac_bugs_that_404.patch", "author": "pythonian4000"}], "history": [{"message": "This is great. It's in origin/master and will be deployed shortly.\n   \n", "author": "paulproteus"}, {"message": "The bug importer on my development server has been getting stuck for a while on\nbug 53 from I2P. Upon investigation, it appears that I2P has completely deleted\nthis bug rather than closing it. This meant that when the importer tried to\nrefresh the stored Bug object corresponding to bug 53, it would crash.\n\nThe supplied patch catches any 404 error that the Trac bug importer throws and\nthen deletes the Bug object corresponding to it from the database.\n   \n", "author": "pythonian4000"}]}