{"status": "chatting", "priority": "wish", "title": "sufjan can't log into MediaWiki", "milestone": "later", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "", "waitingon": "", "keywords": [], "id": "317", "files": [], "history": [{"message": "Yay! (Also maybe that would be a good time to document it some more.)\n   \n", "author": "paulproteus"}, {"message": "-----BEGIN PGP SIGNED MESSAGE-----\nHash: SHA1\n\nI've got my plate full for the next couple of weeks, but after that I\ncan probably pop in and have a fiddle.\n\nCheers\nJack\n\n-----BEGIN PGP SIGNATURE-----\nVersion: GnuPG v1.4.11 (GNU/Linux)\nComment: Using GnuPG with Mozilla - <a href=\"http://enigmail.mozdev.org/\">http://enigmail.mozdev.org/</a>\n\niQEcBAEBAgAGBQJP5SV+AAoJEI3j92WSe+b31E8H/3UcGd15xxG+NWwVQYPghDhp\nhnpFBQ2imD0FpzA6itBTPuSOh/Gz7MgUVxMF7O88ocCHDx5RxkuepSBIVkyz31iH\njTmh08+m1azk5/bYk538AZrUixFiulrr/fioF783TcfKqJR/J1FXUe7GAfMQqsFv\nFpz8EqYy12BbsMAQ/omeaFDAWxE7V2Cjdqo/PbHb8DPWJrAqlOHKpJoIM0w2Z+HD\notoBCHSyXLuD7PjHnA1eXiOMQC8lwJCkXfCcqIyaHFm6Lao3oYMQkcuzjWnuN24m\nj1B6hZCXLIja/WENUz3j10vJM4R5VJnWiTq+6blwrVifPMoROwBl3o5Rgw41M+8=\n=i6WJ\n-----END PGP SIGNATURE-----\n   \n", "author": "pythonian4000"}, {"message": "Good news and bad news.\n\nThe good news is, we diagnosed the 'badtoken' problem. In fact, it's fixed\nthrough a hack to AuthDjango, as discussed on OH-Dev!\n\nThe bad news is I have no idea what is going wrong now because I can't quite\nunderstand MeetBot's configuration.\n\nI'm bumping the priority of this down for now.\n   \n", "author": "paulproteus"}, {"message": "Deassigning myself due to lack of time. Anyone is free to grab it; if they need\nto patch the AuthDjango plugin then do so and I'll happily commit patches to the\nrepo once reviewed.\n   \n", "author": "pythonian4000"}, {"message": "Bumping (again).\n   \n", "author": "pythonian4000"}, {"message": "Hmm, this seems at face value unrelated to the central login system - the site\nlogin works fine (now that I have enabled password login for sufjan) but the\nactual API edit call returns:\n\nAPIError(u'badtoken', u'Invalid token', None)\n\nIt is possible that something in the API is being unintentionally affected by\nthe AuthDjango plugin. I'll have to dig deeper...\n   \n", "author": "pythonian4000"}, {"message": "Bumping.\n   \n", "author": "pythonian4000"}, {"message": "Since the central login system was implemented, sufjan has been unable to log\ninto MediaWiki. This is sad, and causes the MeetBot plugin to fail.\n   \n", "author": "pythonian4000"}]}