{"status": "resolved", "priority": "urgent", "title": "Upgrade openhatch to use Django 1.2.5.", "milestone": "0.11.03", "superceder": "", "nosylist": ["palhmbs, paulproteus"], "assigned": "palhmbs", "waitingon": "", "keywords": [], "id": "359", "files": [{"url": "http://openhatch.org/bugs/file204/0001-Upgrade-Django-recipes-to-use-Django-1.2.5.patch", "author": "palhmbs"}], "history": [{"message": "This is done.\n\nIt left a few broken tests in its wake, but nothing totally totally fatal, I think.\n   \n", "author": "paulproteus"}, {"message": "Another FAIL...\n\n  File \"/media/0fad1c38-da9c-46e6-9352-5419b42cf26a/scripts/palhmbs-oh-mainline/\neggs/xapian_haystack-1.1.5beta-py2.6.egg/xapian_backend.py\", line 799, in \n_database\n    raise InvalidIndexError(u'Unable to open index at %s' % \nsettings.HAYSTACK_XAPIAN_PATH)\nInvalidIndexError: Unable to open index at /media/0fad1c38-\nda9c-46e6-9352-5419b42cf26a/scripts/palhmbs-oh-mainline/mysite/indexes\n\n======================================================================\nFAIL: test_unicode_strings_get_cached (mysite.base.tests.GeocoderCanCache)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/media/0fad1c38-da9c-46e6-9352-5419b42cf26a/scripts/palhmbs-oh-mainline/\nmysite/base/tests.py\", line 197, in test_unicode_strings_get_cached\n    raise AssertionError, \"Geocoded location in json was not cached; it now \nequals \" + json\nAssertionError: Geocoded location in json was not cached; it now equals {\"key\": \n\"if caching works we should never get this value\", \"is_inaccessible\": false}\n\n----------------------------------------------------------------------\nRan 186 tests in 1843.906s\nFAILED (failures=1, errors=8)\n\nI don't know, maybe we should just push it out there.\nSo here is a patch that changes the relevant lines in buildout.cfg.\n   \n", "author": "palhmbs"}, {"message": "It failed...\n\n  File \"/media/0fad1c38-da9c-46e6-9352-5419b42cf26a/scripts/\npalhmbs-oh-mainline/eggs/xapian_haystack-1.1.5beta-py2.6.egg/\nxapian_backend.py\", line 355, in search\n    database = self._database()\n  File \"/media/0fad1c38-da9c-46e6-9352-5419b42cf26a/scripts/\npalhmbs-oh-mainline/eggs/xapian_haystack-1.1.5beta-py2.6.egg/\nxapian_backend.py\", line 799, in _database\n    raise InvalidIndexError(u'Unable to open index at %s' % \nsettings.HAYSTACK_XAPIAN_PATH)\nInvalidIndexError: Unable to open index at /media/0fad1c38-\nda9c-46e6-9352-5419b42cf26a/scripts/palhmbs-oh-mainline/mysite/\nindexes\n\n======================================================================\nFAIL: test_unicode_strings_get_cached \n(mysite.base.tests.GeocoderCanCache)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/media/0fad1c38-da9c-46e6-9352-5419b42cf26a/scripts/\npalhmbs-oh-mainline/mysite/base/tests.py\", line 197, in \ntest_unicode_strings_get_cached\n    raise AssertionError, \"Geocoded location in json was not \ncached; it now equals \" + json\nAssertionError: Geocoded location in json was not cached; it \nnow equals {\"key\": \"if caching works we should never get this \nvalue\", \"is_inaccessible\": false}\n\n----------------------------------------------------------------------\nRan 186 tests in 1860.388s\n\nFAILED (failures=1, errors=8)\n   \n", "author": "palhmbs"}, {"message": "Great -- how did they go? (-:\n   \n", "author": "paulproteus"}, {"message": "Installed and test are now running, thanks.\n   \n", "author": "palhmbs"}, {"message": "I think that you need to install the 'svnadmin' program. Can you get that\ninstalled, and try again?\n\nYou should be able to reproduce the problem whether or not you are on Django 1.2.5.\n\n(It'd be good to fix README to match this.)\n   \n", "author": "paulproteus"}, {"message": "I've started a test following the instructions at <a href=\"http://openhatch.org/wiki/\">http://openhatch.org/wiki/</a>\nAutomated_testing\nI got a error straight off - \n\n  File \"/media/0fad1c38-da9c-46e6-9352-5419b42cf26a/scripts/palhmbs-oh-mainline/\nmysite/testrunner.py\", line 43, in override_settings_for_testing\n    '--root', settings.SVN_REPO_PATH])\n  File \"/usr/lib/python2.6/subprocess.py\", line 483, in check_call\n    retcode = call(*popenargs, **kwargs)\n  File \"/usr/lib/python2.6/subprocess.py\", line 470, in call\n    return Popen(*popenargs, **kwargs).wait()\n  File \"/usr/lib/python2.6/subprocess.py\", line 623, in __init__\n    errread, errwrite)\n  File \"/usr/lib/python2.6/subprocess.py\", line 1141, in _execute_child\n    raise child_exception\nOSError: [Errno 2] No such file or directory\n\nAny ideas?\n   \n", "author": "palhmbs"}, {"message": "As per our meeting this week (<a href=\"https://openhatch.org/meeting-irc-logs/\">https://openhatch.org/meeting-irc-logs/</a>\nweekly/2011-04-02.log.html) --\n20:57:51 &lt;paulproteus&gt; palhmbs: Once you upgrade to Django 1.2.5, if the test \nsuite passes fine, and the web app works fine, we should do that across the \nboard -- submit a patch.\n20:58:08 &lt;paulproteus&gt; If the tests don't all pass, then we need to figure out \nwhat's broken in Django 1.2.5 and fix it.\n   \n", "author": "palhmbs"}]}