{"status": "resolved", "priority": "feature", "title": "Profile import from bitbucket", "milestone": "", "superceder": "", "nosylist": ["Mark, bboissin, paulproteus, rafpaf"], "assigned": "Mark", "waitingon": "", "keywords": [], "id": "59", "files": [{"url": "http://openhatch.org/bugs/file16/0011-Added-live-test-for-bitbucket-import.patch", "author": "Mark"}, {"url": "http://openhatch.org/bugs/file14/bitbucket_import.tar", "author": "Mark"}], "history": [{"message": "I added a few small changes, merged this to master, and deployed it.\n\nYay! Thanks Mark! Your willingness to live by the tests made this super easy for \nme.\n   \n", "author": "paulproteus"}, {"message": "Live test complete and uploaded.\n   \n", "author": "Mark"}, {"message": "Issues with test resolved. No errors or failures now. Updated patch file\nincluded. I still have the *live* test to write, however I'm having trouble with\nmy connection and can't seem to run the existing test first.  Once that is\nresolved, I will update with those test.\n   \n", "author": "Mark"}, {"message": "Excerpts from Mark Freeman's message of Tue May 11 12:22:24 +0000 2010:\n&gt; \n&gt; Mark Freeman &lt;<a href=\"mailto:mark@timewasted.net\">mark@timewasted.net</a>&gt; added the comment:\n&gt; \n&gt; I must have missed this problem yesterday, but the test errors (not fails). I\n&gt; don't think the test itself is necessarily the issue, and I don't think it is in\n&gt; the code that does the import. I think the problem is in\n&gt; _test_data_source_via_emulated_bgtask, in mysite/profile/tests.py\n&gt; \n&gt; On this line.\n&gt; portfolio_entries = PortfolioEntry.objects.filter(project__name='MO     CK\n&gt; ccHost')\n&gt; \n&gt; The error returned here: <a href=\"http://pastebin.com/RXcVY8gg\">http://pastebin.com/RXcVY8gg</a>\n&gt; \n&gt; I *think* this is because project \"Mock ccHost\" doesn't exist and isn't being\n&gt; returned by the query, but it blows up. It seems the method is explicitly\n&gt; checking to make sure it doesn't exist.  Should that check be placed within a\n&gt; try/except or something to suppress the expected error? \n&gt; \n&gt; I may be way off base on what I think the issue is, but if someone wouldn't mind\n&gt; taking a look, that would be great.\n\nI think the problem is that you're not saving a PortfolioEntry in your Bitbucket\nimporter.\n\nRead the Github import source and see if that clears things up?\n\n(I haven't re-read your patch lately, though.)\n   \n", "author": "paulproteus"}, {"message": "I must have missed this problem yesterday, but the test errors (not fails). I\ndon't think the test itself is necessarily the issue, and I don't think it is in\nthe code that does the import. I think the problem is in\n_test_data_source_via_emulated_bgtask, in mysite/profile/tests.py\n\nOn this line.\nportfolio_entries = PortfolioEntry.objects.filter(project__name='MO     CK ccHost')\n\nThe error returned here: <a href=\"http://pastebin.com/RXcVY8gg\">http://pastebin.com/RXcVY8gg</a>\n\nI *think* this is because project \"Mock ccHost\" doesn't exist and isn't being\nreturned by the query, but it blows up. It seems the method is explicitly\nchecking to make sure it doesn't exist.  Should that check be placed within a\ntry/except or something to suppress the expected error? \n\nI may be way off base on what I think the issue is, but if someone wouldn't mind\ntaking a look, that would be great.\n   \n", "author": "Mark"}, {"message": "Test all pass and importer seems to work. Issues with descriptions being set\nresolved.\n   \n", "author": "Mark"}, {"message": "These patches look great!\n\nMark (timewasted), we planned to chat online Sunday evening (8 PM Eastern, as I\nrecall) about how one could write a test for them. I'll hold off on pushing the\npatches into master until we have that conversation.\n\nAlso, you gzip'd the tar file twice, but no big deal.\n\nThis totally rocks.\n   \n", "author": "paulproteus"}, {"message": "Previous file was bad. Uploading a new one.\n   \n", "author": "Mark"}, {"message": "Attached are three patches. I added a new module for actually connecting to and\nreturning the profile results. It is pretty sparse, but I figured we could use\nit to also include the methods for pulling bug tracker items and such in the\nfuture.  I have also included the changes to mysite/profile/models.py and\nmysite/profile/tasks/__init__.py.\n\nThere seems to be one bug that I can't see what the problem is (not sure how to\ndebug things in the running server instance). The project description isn't\ngetting picked up, but does appear to be in the data returned from the json call.\n\nI'll be working on the test.\n   \n", "author": "Mark"}, {"message": "We should support bitbucket as well as github.\n   \n", "author": "paulproteus"}]}