{"status": "resolved", "priority": "bug", "title": "Github importer is generating ParsedBug objects with no _tracker_name value", "milestone": "", "superceder": "", "nosylist": ["jwm, paulproteus"], "assigned": "", "waitingon": "", "keywords": [], "id": "773", "files": [], "history": [{"message": "This is in. Could use more test coverage, but it seems to pass what tests there \nare. (-:\n   \n", "author": "paulproteus"}, {"message": "\n  <a href=\"https://github.com/openhatch/oh-bugimporters/pull/21\">https://github.com/openhatch/oh-bugimporters/pull/21</a>\n\n   \n", "author": "jwm"}, {"message": "It seems to (at least) be true of the Github importer.\n   \n", "author": "paulproteus"}, {"message": "I am running \"python import_bugimporter_data /tmp/results.jsonlines\".\n\nWhat I expect is that it should import JSON data from the file specified without \nprinting any warnings.\n\nWhat I'm seeing instead is this error:\n\n  File \"/home/deploy/milestone-a/mysite/customs/management/commands/import_bugi\nmporter_data.py\", line 49, in handle\n    mysite.customs.core_bugimporters.import_one_bug_item(bug_dict)\n  File \"/home/deploy/milestone-a/mysite/customs/core_bugimporters.py\", line 79,\n in import_one_bug_item\n    tracker_name=d['_tracker_name'])\nKeyError: '_tracker_name'\n\nI believe we should adjust oh-bugimporters so that it refuses to export any \nParsedBug item that doesn't have a _tracker_name value.\n\n(My guess for the root cause here is that there's probably a bug in one of the \nbugimporter classes where it's not filling in the _tracker_name value.)\n\nWe can possibly do this with the help of an undocumented property of the scrapy \nField class: \"required\". You can see that here: \n<a href=\"http://pydoc.net/s01.scrapy/0.12.3/s01.scrapy.fieldproperty\">http://pydoc.net/s01.scrapy/0.12.3/s01.scrapy.fieldproperty</a>\n\nAn alternative is to add some of our own machinery that insists ParsedBug has \nthis field set to a value.\n   \n", "author": "paulproteus"}]}