{"status": "resolved", "priority": "bug", "title": "bugzilla bug importer crashes with AttributeError", "milestone": "", "superceder": "", "nosylist": ["paulproteus"], "assigned": "", "waitingon": "", "keywords": [], "id": "790", "files": [], "history": [{"message": "I fixed this in\n<a href=\"https://github.com/openhatch/oh-bugimporters/commit/211c607ff828784c81904c26a89f33b9ff43b37c\">https://github.com/openhatch/oh-bugimporters/commit/211c607ff828784c81904c26a89f33b9ff43b37c</a>\n   \n", "author": "paulproteus"}, {"message": "When handle_query_response() gets a tracking bug XML response, it crashes.\n\nSample URL: <a href=\"https://bugzilla.redhat.com/show_bug.cgi?ctype=xml&amp;id=509829\">https://bugzilla.redhat.com/show_bug.cgi?ctype=xml&amp;id=509829</a>\n\n          File \"/home/deploy/oh-bugimporters/bugimporters/bugzilla.py\", line 84, in \nhandle_query_response\n            bug_ids = self.handle_tracking_bug_xml(response.body)\n\n          File \"/home/deploy/oh-bugimporters/bugimporters/bugzilla.py\", line 123, in \nhandle_tracking_bug_xml\n            self.bug_ids.extend([int(depend.text) for depend in depends])\n        exceptions.AttributeError: 'BugzillaBugImporter' object has no attribute 'bug_ids'\n\nWe should be returning bug_ids, not modifying self.bug_ids. We should make sure this particular case \ngets covered in the test suite.\n\nTo fix this, take the following steps:\n\n* Create a new test method in some existing class in \nbugimporters/tests/test_bugzilla.py \n\n* Make sure the above URL appears in the list of queries for the TrackerModel \n(usually self.tm or \"tm\").\n\n* Then run the test suite and watch it crash. Fix the crashes and now you'll get \nbugs imported in the test.\n\nYay.\n   \n", "author": "paulproteus"}]}