{"status": "resolved", "priority": "bug", "title": "Very strange 404, possibly a Python 2.6 issue", "milestone": "", "superceder": "", "nosylist": ["rafpaf"], "assigned": "", "waitingon": "", "keywords": ["python2.6"], "id": "80", "files": [{"url": "http://openhatch.org/bugs/file21/404_error_page", "author": "rafpaf"}], "history": [{"message": "This was a bug in some code that I wrote, not in Python 2.6. It took down the\nsite a bunch of times. Hooray. It's been fixed, though.\n\nMoral: Let's not assume so quickly that Python 2.6 is to blame.\n   \n", "author": "rafpaf"}, {"message": "(yargh, Python 2.6 errors.)\n   \n", "author": "paulproteus"}, {"message": "Try running a local server and visiting\n<a href=\"http://localhost:8000/account/settings/location/?asdf\">http://localhost:8000/account/settings/location/?asdf</a>\n\nGives you 404. Now remove the query string. At the moment that works fine on my\nmachine. Very strange!\n   \n", "author": "rafpaf"}]}