{"status": "resolved", "priority": "bug", "title": "Roundup importer breaks on new project", "milestone": "", "superceder": "", "nosylist": ["pythonian4000"], "assigned": "", "waitingon": "", "keywords": [], "id": "98", "files": [{"url": "http://openhatch.org/bugs/file29/roundup_importer_no_longer_breaks_on_new_projects.patch", "author": "pythonian4000"}], "history": [{"message": "This is great. Committed and pushed!\n   \n", "author": "paulproteus"}, {"message": "Runing a fresh import of bugs today, the Roundup importer was failing. Turns out\nthat the importer was calling:\n\nself.project = mysite.search.models.Project.objects.get(name=project_name)\n\nto get a Project, which failed since none of the Roundup Projects existed. The\nsupplied patch changed this call to:\n\nself.project, _ =\nmysite.search.models.Project.objects.get_or_create(name=project_name)\n   \n", "author": "pythonian4000"}]}